version: 2.1
jobs:
  semgrep-scan:
    parameters:
      repo_path:
        type: string
        default: callmeashish/Leetcode-Python
      default_branch:
        type: string
        default: main
    environment:
      # SEMGREP_RULES: >- # more at semgrep.dev/explore
      #   p/security-audit
      #   p/secrets

      # Scan changed files in PRs, block on new issues only (existing issues ignored)
      SEMGREP_BASELINE_REF: << parameters.default_branch >>

    # == Optional settings in the `environment:` block

    # Instead of `SEMGREP_RULES:`, use rules set in Semgrep App.
    # Get your token from semgrep.dev/manage/settings.
      SEMGREP_APP_TOKEN: 2c33ce39000fcaf25c9d21b5bd02125597319ff46635509a359a57371c0c2c66
      SEMGREP_REPO_NAME: Leetcode-Python
      SEMGREP_REPO_URL: https://github.com/callmeashish/Leetcode-Python.git
      SEMGREP_BRANCH: main

    # Never fail the build due to findings.
    # Instead, just collect findings for semgrep.dev/manage/findings
    #   SEMGREP_AUDIT_ON: unknown

    # Change job timeout (default is 1800 seconds; set to 0 to disable)
    #   SEMGREP_TIMEOUT: 300

    docker:
      - image: returntocorp/semgrep-agent:v1
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep-agent
workflows:
  main:
    jobs:
      - semgrep-scan
